all:
	gcc -g -rdynamic /media/umass/datasystem/tongping/numalloc/source/libnumalloc.so -O0 -o testprivatesite testprivatesite.cpp
#gcc -O2 -o alloc-tcmalloc alloc.cpp -rdynamic /media/umass/datasystem/tongping/tcmalloc/tcmalloc-2.7/.libs/libtcmalloc.so
